# Generated by Django 4.0.7 on 2023-05-31 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('razonsoc', models.CharField(max_length=30)),
                ('fantasia', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=15)),
                ('localidad', models.CharField(max_length=20)),
                ('cpostal', models.CharField(max_length=4)),
                ('cpa', models.CharField(max_length=8)),
                ('cuit', models.CharField(max_length=13)),
                ('cm', models.CharField(max_length=14)),
                ('cativa', models.CharField(max_length=1)),
                ('compro', models.CharField(max_length=1)),
                ('fecini', models.DateField()),
                ('telefono', models.CharField(db_column='Telefono', max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('web', models.CharField(max_length=30)),
                ('deniva', models.CharField(max_length=25)),
                ('cate', models.CharField(max_length=1)),
                ('sucursal', models.CharField(max_length=3)),
                ('smtpserver', models.CharField(max_length=30)),
                ('sendpassword', models.CharField(max_length=20)),
                ('central', models.IntegerField()),
                ('eslogan', models.CharField(max_length=50)),
                ('idemp', models.CharField(max_length=2, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=15)),
                ('localidad', models.CharField(max_length=20)),
                ('comentario', models.TextField()),
                ('cpa', models.CharField(max_length=8)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('central', models.IntegerField()),
                ('activo', models.IntegerField()),
                ('esucursal', models.IntegerField()),
                ('fh', models.DateTimeField()),
            ],
            options={
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idusu', models.IntegerField()),
                ('usuario', models.CharField(max_length=20)),
                ('passd', models.CharField(max_length=40)),
                ('fechap', models.DateField()),
                ('area', models.CharField(max_length=2)),
                ('secc', models.IntegerField()),
                ('nivel', models.IntegerField()),
                ('idemp', models.CharField(max_length=2)),
                ('fh', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
