# Generated by Django 4.0.7 on 2023-05-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisisweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursales',
            name='id',
        ),
        migrations.AlterField(
            model_name='sucursales',
            name='sucursal',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
