# Generated by Django 4.0.7 on 2023-06-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisisweb', '0002_remove_sucursales_id_alter_sucursales_sucursal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='idusu',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
