# Generated by Django 4.0.7 on 2023-06-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisisweb', '0003_remove_usuarios_id_alter_usuarios_idusu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursales',
            options={'managed': False},
        ),
    ]
