# Generated by Django 4.0.7 on 2023-06-02 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisisweb', '0004_alter_sucursales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursales',
            options={},
        ),
    ]
