# Generated by Django 4.0.7 on 2023-06-13 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisisweb', '0006_alter_sucursales_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codart', models.IntegerField(blank=True, null=True)),
                ('ecodart', models.IntegerField()),
                ('proveedor', models.CharField(blank=True, max_length=3, null=True)),
                ('eproveedor', models.IntegerField()),
                ('articulo', models.CharField(blank=True, max_length=15, null=True)),
                ('descrip', models.CharField(blank=True, max_length=90, null=True)),
                ('embalaje', models.CharField(blank=True, max_length=2, null=True)),
                ('color', models.CharField(blank=True, max_length=2, null=True)),
                ('grupo', models.CharField(blank=True, max_length=12, null=True)),
                ('marca', models.CharField(blank=True, max_length=3, null=True)),
                ('poferta', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio1', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio2', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio3', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('precio4', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('oferta', models.IntegerField()),
                ('plpciva', models.IntegerField()),
                ('calcula', models.IntegerField()),
                ('nppedido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ncpedir', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nodesc', models.IntegerField(blank=True, null=True)),
                ('noutil', models.IntegerField()),
                ('nutil', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('niva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ncostop', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ncostov', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('naum', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('ubica', models.CharField(blank=True, max_length=3, null=True)),
                ('fecham', models.DateField()),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('iddiv', models.IntegerField(blank=True, null=True)),
                ('colref', models.IntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=35, null=True)),
                ('ldsp', models.IntegerField(blank=True, null=True)),
                ('c002', models.IntegerField(blank=True, null=True)),
                ('ec002', models.IntegerField()),
                ('proveedor2', models.CharField(blank=True, max_length=3, null=True)),
                ('eproveedor2', models.IntegerField()),
                ('embalaje2', models.CharField(blank=True, max_length=2, null=True)),
                ('color2', models.CharField(blank=True, max_length=2, null=True)),
                ('grupo2', models.CharField(blank=True, max_length=12, null=True)),
                ('marca2', models.CharField(blank=True, max_length=3, null=True)),
                ('fh', models.DateTimeField()),
            ],
            options={
                'db_table': 'articulos',
            },
        ),
        migrations.AlterModelOptions(
            name='sucursales',
            options={},
        ),
    ]
